name: Main

on:
  push:

jobs:
  get-outputs:
    name: Get skip-deploy and skip-chromatic outputs
    runs-on: ubuntu-latest
    outputs:
      skip-deploy: ${{ steps.skip-deploy.outputs.skip-deploy }}
      skip-chromatic: ${{ steps.skip-chromatic.outputs.skip-chromatic }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - run: |
          cd .github/scripts
          npm ci --omit=dev # We don't want to install jest and its dependencies
      - id: skip-deploy
        uses: actions/github-script@v6
        with:
          script: |
            const script = require('.github/scripts/skip-output.js');
            script({github, context, core}, 'skip-deploy');
      - id: skip-chromatic
        uses: actions/github-script@v6
        with:
          script: |
            const script = require('.github/scripts/skip-output.js');
            script({github, context, core}, 'skip-chromatic');
