name: Main

on:
  push:

jobs:
  get-outputs:
    name: Get skip-deploy and skip-chromatic outputs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/github-script@v6
        with:
          script: |
            const script = require('.github/scripts/skip-output.js');
            script({github, context});
